export const COLOR_SWATCH_MAP: Record<string, string> = {
    red: "#E94235",
    orange: "#FF8A3C",
    yellow: "#F6E36C",
    green: "#3BB273",
    blue: "#3A7BEB",
    navy: "#1D3C78",
    purple: "#8E44AD",
    pink: "#FF5D8F",
    hotpink: "#FF69B4",
    deeppink: "#FF1493",
    lightpink: "#FFB6C1",
    black: "#111111",
    white: "#FAFAFA",
    grey: "#D9D9D9",
    gray: "#D9D9D9",
    brown: "#9B5B2A",
    gold: "#FFD700",
    silver: "#C0C0C0",
    beige: "#F5F5DC",
    cream: "#FFFDD0",
    maroon: "#800000",
    teal: "#008080",
    coral: "#FF7F50",
    olive: "#808000",
    mint: "#98FF98",
    lavender: "#E6E6FA",
    cyan: "#00FFFF",
    turquoise: "#40E0D0",
    sky: "#87CEEB",
    indigo: "#4B0082",
    violet: "#EE82EE",
    magenta: "#FF00FF",
    lime: "#00FF00",
    charcoal: "#36454F",
    slate: "#708090",
    crimson: "#DC143C",
    khaki: "#F0E68C",
    aqua: "#00FFFF",
    peach: "#FFDAB9",
}

export const STANDARD_COLORS = [
    "Red", "Blue", "Green", "Black", "White",
    "Yellow", "Orange", "Purple", "Pink", "HotPink",
    "DeepPink", "LightPink", "Brown", "Grey", "Gold",
    "Silver", "Cyan", "Magenta", "Maroon", "Navy",
    "Olive", "Teal", "Lime", "Aqua", "Indigo",
    "Violet", "Coral", "Crimson", "Khaki", "Lavender",
    "Beige", "Turquoise", "Peach"
]
